### ISSUE TITLE
is possible using this console without hardware esp?

### ISSUE THREAD

**Issue by sp00ck** [mruby-esp32/mruby-esp32-app-mirb#1]
Is possible to using it without hardware?
Is any benchmark or information about memory consumption?

What You think about mrubyc joining to this project? https://github.com/mrubyc/mrubyc

**Comment by pandax381** [comment]
This project was developed for ESP32.
The part of STDIO is platform dependent. (But, it's may work with a little fix)

Also there is no benchmark result.

This program depends on mruby-bin-mirb mgem.
Therefore, it can not be run with mruby/c.

If I have time to spare, I think I will do the same thing with mruby/c.
